version: '3.8'

services:
  simple-node-app:
    image: localhost:8082/repojenkins/simple-node-app:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    restart: always
